// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('postmo.normal.budi', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('postmo.normal.budi', async function() {
    await driver.get("http://localhost/meetroom/bookpostmo-index-today")
    await driver.manage().window().setRect({ width: 1382, height: 738 })
    await driver.findElement(By.css(".fa-plus")).click()
    await driver.findElement(By.id("name")).click()
    await driver.findElement(By.id("name")).sendKeys("postmo - budi")
    await driver.findElement(By.id("phone_ext")).click()
    await driver.findElement(By.id("phone_ext")).sendKeys("111")
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("budi@gmail.com")
    await driver.findElement(By.id("participants")).click()
    await driver.findElement(By.id("participants")).sendKeys("3")
    await driver.findElement(By.id("meetingdt")).click()
    await driver.findElement(By.css(".today")).click()
    await driver.findElement(By.id("meetingdt")).sendKeys("13/11/2023")
    await driver.findElement(By.id("startdt")).click()
    await driver.findElement(By.id("startdt")).sendKeys("08:00")
    await driver.findElement(By.id("enddt")).click()
    await driver.findElement(By.css(".open .flatpickr-hour")).sendKeys("10")
    await driver.findElement(By.id("enddt")).sendKeys("10:00")
    await driver.findElement(By.id("subject")).click()
    await driver.findElement(By.id("subject")).sendKeys("postmo - meeting internal arsitek")
    await driver.findElement(By.id("description")).click()
    await driver.findElement(By.id("description")).sendKeys("postmo - meeting internal arsitek: perencanaan")
    await driver.findElement(By.css(".fa-save")).click()
    await driver.findElement(By.linkText("Today")).click()
    await driver.findElement(By.css("td:nth-child(3)")).click()
  })
})
